OPENAI_API_KEY = "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"
PINECONE_API_KEY = "33045f70-074b-449b-85ed-a09cb1469f75"
PINECONE_ENVIRONMENT = "asia-southeast1-gcp-free"
PINECONE_INDEX_NAME = "youtube-app"
PINECONE_ENDPOINT = "youtube-app-004922c.svc.asia-southeast1-gcp-free.pinecone.io"


